name: 💡 Feature Request
description: Suggest an idea or new feature for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Feature - Completely new functionality
        - Enhancement - Improvement to existing feature
        - UI/UX Improvement - Better user experience
        - Performance - Speed or efficiency improvement
        - Documentation - Better docs or examples
        - Developer Experience - Better DX or tooling
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I'd like to see... / The feature should work like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... / Another approach could be...
    validations:
      required: false

  - type: dropdown
    id: target-version
    attributes:
      label: Target Version
      description: Which version should this feature be added to?
      options:
        - Local Version (Flask + Docker)
        - Demo Version (Browser-only SPA)
        - Both Versions
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      options:
        - End Users (nutrition tracking)
        - Developers (code/architecture)
        - DevOps (deployment/operations)
        - QA Engineers (testing)
        - Product Owners/Managers
        - All Users
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. When a user wants to...
        2. When a developer needs to...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add mockups, screenshots, or links to similar features in other apps
      placeholder: Drag and drop images or paste links...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Critical - Can't use the app without it
        - High - Very important, would significantly improve experience
        - Medium - Nice to have, would improve experience
        - Low - Not urgent, but would be beneficial
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Hints
      description: If you have technical implementation ideas, share them here
      placeholder: This could be implemented by... / Possible approach...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information about the feature request
      placeholder: Additional details...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and PRs to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the project's goals (nutrition tracking, education, FOSS)
          required: true
        - label: I am willing to help implement this feature (if possible)
          required: false
