name: ❓ Question or Help
description: Ask a question or request help
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide details so we can assist you better.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation & Setup
        - Usage & Features
        - Configuration
        - Troubleshooting
        - Development & Contributing
        - Architecture & Design
        - Testing
        - Deployment
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I... / Why does... / What is the best way to...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to do
      placeholder: I'm trying to... / I want to achieve...
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken?
      placeholder: I've tried... / I've checked...
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      options:
        - Local Version (Flask + Docker)
        - Demo Version (Browser-only SPA)
        - Both
        - Not sure
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might help us answer your question
      placeholder: Additional context...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation (README.md, docs/)
          required: true
        - label: I have searched existing issues and discussions
          required: true
