#!/bin/bash
# Build script for Public version (with Storage adapter)
#
# This script builds the frontend for the Public version which uses
# the StorageAdapter to store data in LocalStorage.

set -e

echo "🔨 Building Nutricount Public Version..."

# Configuration
FRONTEND_DIR="frontend"
OUTPUT_DIR="frontend/build/public"
SRC_DIR="$FRONTEND_DIR/src"

# Create output directory
echo "📁 Creating output directory..."
mkdir -p "$OUTPUT_DIR"

# Copy demo HTML template if it exists
if [ -f "demo/index.html" ]; then
    echo "📄 Copying demo HTML template..."
    cp demo/index.html "$OUTPUT_DIR/index.html"
fi

# Concatenate JavaScript files
echo "📦 Bundling JavaScript..."
cat > "$OUTPUT_DIR/app.js" << 'EOF'
// Nutricount Public Version - Built with StorageAdapter
// Auto-generated by build-public.sh

EOF

# Add backend adapter interface
cat "$SRC_DIR/adapters/backend-adapter.js" >> "$OUTPUT_DIR/app.js"
echo "" >> "$OUTPUT_DIR/app.js"

# Add Storage adapter
cat "$SRC_DIR/adapters/storage-adapter.js" >> "$OUTPUT_DIR/app.js"
echo "" >> "$OUTPUT_DIR/app.js"

# Add business logic
cat "$SRC_DIR/business-logic/nutrition-calculator.js" >> "$OUTPUT_DIR/app.js"
echo "" >> "$OUTPUT_DIR/app.js"

cat "$SRC_DIR/business-logic/validators.js" >> "$OUTPUT_DIR/app.js"
echo "" >> "$OUTPUT_DIR/app.js"

# Add initialization code
cat >> "$OUTPUT_DIR/app.js" << 'EOF'

// Initialize application with Storage adapter
(function() {
    'use strict';
    
    // Create adapter
    const adapter = new StorageAdapter();
    
    // Make adapter globally available
    window.nutritionAdapter = adapter;
    
    console.log('✅ Nutricount Public Version initialized with Storage adapter');
})();
EOF

# Copy manifest for PWA support
if [ -f "demo/manifest.json" ]; then
    echo "📋 Copying PWA manifest..."
    cp demo/manifest.json "$OUTPUT_DIR/manifest.json"
fi

echo "✅ Build complete!"
echo "📁 Output: $OUTPUT_DIR"
echo ""
echo "🚀 To deploy to GitHub Pages:"
echo "   1. Copy contents of $OUTPUT_DIR to gh-pages branch"
echo "   2. Push to GitHub"
echo "   3. Enable GitHub Pages in repository settings"
echo ""
echo "💻 To test locally:"
echo "   cd $OUTPUT_DIR && python3 -m http.server 8000"
echo "   Open http://localhost:8000"
